[package]
name = "ffmpeg-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
ffmpeg-next = { version = "5.0.2" }
opencv = { version = "0.61.1", features = ["clang-runtime", "rgb"]}
rayon = "1.5.2"
rgb = "0.8.30"
tokio = { version = "1.18.1", features = ["full"] }
flume = "0.10.12"
